version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - mongo
  mongo:
    container_name: postgres
    image: postgres:12
    networks:
      - webnet
    environment:
      MONGO_PASSWORD: ${DB_PASSWORD}
      MONGO_USER: ${DB_USERNAME}
      MONGO_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/mongo/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/mongo/data
networks:
  webnet:
volumes:
  pgdata: